version: "3.8"
services:
  api:
    container_name: preserve-api
    init: true
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_PRESERVE_API_DSN=${SENTRY_PRESERVE_API_DSN:-}
      - YOUTUBE_DL_SKIP_DOWNLOAD=true
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    entrypoint: /home/node/entrypoint.sh
    ports:
      - "4000:4000"
    volumes:
      - ./files:/home/node/app/files
    depends_on:
      - mongo

  worker:
    init: true
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - MONGO_URI=mongodb://mongo
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_PRESERVE_WORKER_DSN=${SENTRY_PRESERVE_WORKER_DSN:-}
      - YOUTUBE_DL_SKIP_DOWNLOAD=true
      - VIDEO_DOWNLOADER_PATH=/usr/local/bin/yt-dlp
    entrypoint: /home/node/worker-entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./files:/home/node/app/files
    depends_on:
      - mongo

  mongo:
    container_name: preserve-mongodb
    restart: unless-stopped
    image: "mongo:5.0"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
