version: "3"
services:
  api:
    container_name: huridocs-vault-api
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/user/app/data
      - ./src:/home/user/app/src
    depends_on:
      - mongo

  mongo:
    container_name: huridocs-vault-mongodb
    restart: unless-stopped
    command: mongod --port 27017
    image: "mongo:5.0.0"
    ports:
      - "27017:27017"
