version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/home/user/app/
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/home/user/app/
  mongo:
    ports:
      - "27019:27017"
