version: "3.8"
services:
  api:
    container_name: preserve-api
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - SENTRY_VAULT_API_DSN=${SENTRY_VAULT_API_DSN}
      - YOUTUBE_DL_SKIP_DOWNLOAD=true
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    entrypoint: /bin/entrypoint.sh
    volumes:
      - ./downloads:/home/user/app/downloads
    depends_on:
      - mongo
    healthcheck:
      test: wget -v http://localhost:4000/api/health
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s

  worker:
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - SENTRY_VAULT_API_DSN=${SENTRY_VAULT_API_DSN}
      - YOUTUBE_DL_SKIP_DOWNLOAD=true
      - VIDEO_DOWNLOADER_PATH=/usr/local/bin/yt-dlp
    entrypoint: /bin/worker-entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./downloads:/home/user/app/downloads
    depends_on:
      - mongo


  mongo:
    container_name: preserve-mongodb
    network_mode: host
    restart: unless-stopped
    command: mongod --port 27019
    image: "mongo:5.0.0"
