version: "3"
services:
  api:
    container_name: preserve-api
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SENTRY_VAULT_API_DSN=${SENTRY_VAULT_API_DSN}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/node/app/data
      - ./downloads:/home/node/app/downloads
    depends_on:
      - mongo

  mongo:
    container_name: preserve-mongodb
    network_mode: host
    restart: unless-stopped
    command: mongod --port 27019
    image: "mongo:5.0.0"
