version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - ./downloads:/home/user/app/downloads
      - ./src:/home/user/app/src
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - ./downloads:/home/user/app/downloads
      - ./src:/home/user/app/src
  mongo:
    ports:
      - "27019:27017"
