version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - ./src:/home/node/app/src
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - ./src:/home/node/app/src
  mongo:
    ports:
      - "27019:27017"
