#!/bin/bash

set -eo pipefail

function test {
  docker exec -it preserve-api env TERM=xterm-256color yarn test "${@}"
}

function test:integration {
  docker exec -it preserve-api env TERM=xterm-256color yarn test-integration "${@}"
}

function start {
  docker-compose up --build -d "${@}"
}

function start:local {
  docker-compose -f docker-compose.yml -f docker-compose.local.yml up --build -d "${@}"
}

function bash:api {
  docker exec -it preserve-api /bin/bash
}

function mongo {
  docker exec -it preserve-mongodb mongo localhost/preserve
}

function stop {
  docker-compose stop
}

function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
