#!/bin/bash

set -eo pipefail

function test {
  docker exec -it huridocs-vault-api env TERM=xterm-256color /bin/bash -c 'cd /home/user/source; yarn test'
}

function remove_docker_containers {
  docker-compose ps -q | xargs docker rm
}

function remove_docker_images {
  docker-compose config --images | xargs docker rmi
}

function start {
  docker-compose up --build -d "${@}"
}

function start:local {
  docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d "${@}"
}

function start:testing {
  docker-compose --profile testing up --build "${@}"
}

function stop {
  docker-compose --profile testing stop
}

function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
