#!/bin/bash

set -eo pipefail

function start {
  docker pull ghcr.io/huridocs/preserve-base:latest && docker-compose up --build -d "${@}"
}

function start:local {
  docker pull ghcr.io/huridocs/preserve-base:latest && docker-compose -f docker-compose.yml -f docker-compose.local.yml up --build -d "${@}"
}

function bash:api {
  docker exec -it preserve-api /bin/bash
}

function mongo {
  docker exec -it preserve-mongodb mongo localhost/preserve
}

function stop {
  docker-compose stop
}

function docker:build {
  docker build -f base.Dockerfile -t ghcr.io/huridocs/preserve-base:latest .
}

function docker:push {
  docker push ghcr.io/huridocs/preserve-base:latest
}

function test:unit {
  docker exec preserve-api yarn test
}

function test:integration {
  docker exec preserve-api yarn test-integration
}

function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
