name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0.0
        ports:
          - 27019:27017
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install yt-dlp
        run: sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: install dependencies
        run: yarn install
      - name: Run test suite
        run: yarn test
  integration:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0.0
        ports:
          - 27019:27017
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: install dependencies
        run: yarn install
      - name: Run test suite
        run: yarn test-integration
