name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run testing environment
        run: ./run start:local
      - name: Run test suite
        run: ./run test
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run testing environment
        run: ./run start:local
      - name: Run test suite
        run: yarn test-integration
