name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0.0
        ports:
          - 27017/tcp
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.3'
      - name: install dependencies
        run: yarn install
      - name: Run test suite
        run: yarn test
