name: Run tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker-compose stack
        run: ./run start:local
       - name: Run test suite
         run: docker exec preserve-api yarn test
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker-compose stack
        run: ./run start:local
      - name: Run test suite
        run: docker exec preserve-api yarn test-integration
